jenkins:
    securityRealm:
        local:
            allowsSignup: false
            users:
              - id: admin
                password: password
    authorizationStrategy:
        roleBased:
            roles:
                global:
                  - name: "admin"
                    description: "Jenkins administrators"
                    permissions:
                      - "Overall/Administer"
                    entries:
                      - user: "admin"
